events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    server_tokens off;
    gzip on;
    gzip_types text/plain text/css application/json;

    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;

    upstream backend_pool {
        least_conn; 
        server backend1:3001 max_fails=3 fail_timeout=30s;
        server backend2:3001 max_fails=3 fail_timeout=30s;
        server backend3:3001 max_fails=3 fail_timeout=30s;
        server backend4:3001 max_fails=3 fail_timeout=30s;
        keepalive 32; 
    }

    server {
        listen 80;
        server_name localhost;

        location /api {
            limit_req zone=mylimit burst=5 nodelay;

            proxy_pass http://backend_pool;

            proxy_set_header Host yash-b.onrender.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;


            proxy_connect_timeout 5s;
            proxy_read_timeout 15s;
        }

        location / {
            proxy_pass http://frontend:5173;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        error_page 502 /502.html;
        location = /502.html {
            root /usr/share/nginx/html;
            internal;
        }
    }
}